version: "3"
services:
  proxysql:
    image: proxysql/proxysql:2.0.6
    volumes: 
    - "./proxysql.cnf:/etc/proxysql.cnf"
    - "./proxysql:/var/lib/proxysql"
    ports:
    - "6033:6033"
    - "6032:6032"
    - "6080:6080"